### ISSUE TITLE
fact/k registerized has wrong fact1-cont?

### ISSUE THREAD

**Issue by cacaegg** [mwand/eopl3#12]
Hi, Mitch

In the page 195, the fact/k registerized figure 6.1, it shows the fact1-cont as below:

```
(define apply-cont
  (lambda ()
    (cases continuation cont
      (end-cont () val)
      (fact1-cont (saved-n saved-cont)
        (begin
          (set! cont saved-cont)
          (set! n saved-n)
          (apply-cont))))))
```

The fact1-cont continuation should change the register val as below:

```
(fact1-cont (saved-n saved-cont)
        (begin
          (set! cont saved-cont)
          (set! val (* val saved-n))  ;; changed here
          (apply-cont)))
```

So that we can have correct val register in the final end-cont.
Is that correct?

**Comment by mwand** [comment]
Your code is correct, of course.   In my pdf of the book, this correction has already been applied.  I do not know why this is not in errata.txt .

**Comment by mwand** [comment]
Added this correction, and the corresponding correction for Figure 6.2, to errata.txt .
