### ISSUE TITLE
CPS transformer from chapter 6 doesn’t handle variable scope correctly

### ISSUE THREAD

**Issue by EFanZh** [mwand/eopl3#19]
Try to run this program using a interpreter from chapter 6:

```
let x = 4
in -(let x = 6 in x, x)
```

The result should be 2, but the interpreter produces 0.

**Comment by mwand** [comment]
Hmm, I will have to track this down.

**Comment by mwand** [comment]
OK, the code for `cps-of-let-exp` is wrong because it puts `k-exp `inside the scope of `id`.  The correct code is
````
 (define cps-of-let-exp
    (lambda (id rhs body k-exp)
      (cps-of-exp
       (call-exp
        (proc-exp (list id) body)
        (list rhs))
       k-exp)))
````
I will be pushing the correct code shortly.
