### ISSUE TITLE
Incorrect code sample in exercise 7.28

### ISSUE THREAD

**Issue by EFanZh** [mwand/eopl3#20]
I think the code sample should be fixed as follow:

```diff
- let
+ letrec
   ? map (f : ?) =
      letrec
       ? foo (x : ?) = if null?(x)
                       then emptylist
                       else cons((f car(x)),
-                                ((foo f) cdr(x)))
+                                ((map f) cdr(x)))
      in foo
  in letrec
      ? even (y : ?) = if zero?(y)
                       then zero?(0)
                       else if zero?(-(y,1))
                            then zero?(1)
                            else (even -(y,2))
     in pair(((map proc(x : int)-(x,1))
             cons(3,cons(5,emptylist))),
             ((map even)
              cons(3,cons(5,emptylist))))
```

**Comment by mwand** [comment]
No, I think the code is correct as given.  Your change doesn't break the code, but it makes it more obscure.

**Comment by mwand** [comment]
No, I'm sorry.  You are right.  The code as written is definitely wrong.
Writing ((map f) cdr(x)) as you propose ought to work, though that would make false the sentence below the code, "This expression uses map twice".
Most likely the line in question should have been (f (cdr(x)) .
I will update the errata.   Thank you for your close reading!!
