### ISSUE TITLE
Errata for Page 303

### ISSUE THREAD

**Issue by chansey97** [mwand/eopl3#21]
Hi, Mitch

From page 303
```scheme
(define-datatype type-environment type-environment?
  (empty-tenv)
  (extend-tenv ...as before...)
  (extend-tenv-with-module ...as before...)
  (extend-tenv-with-type
   (name type?)  ; <----- this should be (name symbol?)
   (type type?)
   (saved-tenv type-environment?)))
```

The code on GitHub is correct, but errata is not updated.

Regards,
chansey97

**Comment by mwand** [comment]
Where did you find a copy of the errata?   www.eopl3.com seems to be unreachable right now (Monday 12/3).

**Comment by chansey97** [comment]
@mwand 
Yes, www.eopl3.com seems to be unreachable, but I found the errata from repository:
https://github.com/mwand/eopl3/blob/master/errata.txt 
https://github.com/mwand/eopl3/blob/master/errata.html

**Comment by mwand** [comment]
Added to errata.txt.
Thanks again.
