### ISSUE TITLE
Errata for Page 341 and 362

### ISSUE THREAD

**Issue by chansey97** [mwand/eopl3#22]
Hi, Mitch

From page 341
```
(define apply-method
  (lambda (m self args)
    (cases method m
      (a-method (vars body super-name field-names)
                (value-of body
                          (extend-env* vars (map newref args)
                                       (extend-env-with-self-and-super
                                        self super-name
                                        (extend-env field-names (object->fields self) ; <---- should be extend-env*
                                                    (empty-env)))))))))
```

From page 362, line -2 of the display

> It then goes through each class or instance declaration

"instance " should be "interface" 

Regards,
chansey97

**Comment by mwand** [comment]
Yes, that should definitely be extend-env* .  You are probably right about the typo on page 362.  I see neither of these is in my local copy of the errata. I will fix the website sometime, but right now it seems to be inaccessible.

**Comment by mwand** [comment]
Re page 341:  I should have looked more closely at the code before responding.  It's the extend-env* that's wrong.   Look at the code in the repo.

Re page 362: Yes, that should definitely be "interface".

I will update the errata.txt on github.
Thanks for your close reading!!
