### ISSUE TITLE
SLLGEN cannot report error when input string is illegal.

### ISSUE THREAD

**Issue by chansey97** [mwand/eopl3#26]
Run `chapter6/cps-lang/cps-in-lang.scm` in DrRacket and attempt to parse the following string:

```
(just-scan "(foo 123abc)")

;; ((literal-string51 "(" 1)
;;  (identifier foo 1)
;;  (number 123 1)
;;  (identifier abc 1)
;;  (literal-string51 ")" 1))

(scan&parse "(foo 123abc)")

;; #(struct:a-program
;;   #(struct:call-exp
;;     #(struct:var-exp foo)
;;     (#(struct:const-exp 123) #(struct:var-exp abc))))
```

Notice that the input program has a syntax error, i.e.`123abc` is neither a number nor an identifier. 

The expected behavior is to report a error, but SLLGEN give the wrong AST, which has no syntax error. 

That means we cannot detect this error by traverse the AST in the subsequent pass.

My current workaround is to add a new `Regexp-and-action` in `the-lexical-spec`.

It makes `123abc` a legal identifier:

```
(define the-lexical-spec
  '((whitespace (whitespace) skip)
    (comment ("%" (arbno (not #\newline))) skip)
    (identifier
     (letter (arbno (or letter digit "_" "-" "?")))
     symbol)
    (identifier ;; <----- new `Regexp-and-action`
     (digit (arbno digit) (or letter "_" "-" "?") (arbno (or letter digit "_" "-" "?")))
     symbol)
    (number (digit (arbno digit)) number)
    (number ("-" digit (arbno digit)) number)
    ))
```

But this seems not a good way. 

Can SLLGEN report error when scanning the input characters.

Thanks.

**Comment by mwand** [comment]
By my reading of this spec, there is no requirement that tokens be separated by whitespace.   So 123abc is correctly scanned as two tokens: the number 123 and the identifier abc.
